-- MySQL Script generated by MySQL Workbench
-- Tue May 14 17:51:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tiendacastinblanco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendacastinblanco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendacastinblanco` DEFAULT CHARACTER SET latin1 ;
USE `tiendacastinblanco` ;

-- -----------------------------------------------------
-- Table `tiendacastinblanco`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendacastinblanco`.`banco` (
  `ban_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ban_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `ban_imagen` TEXT NULL DEFAULT NULL,
  `ban_estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ban_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tiendacastinblanco`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendacastinblanco`.`usuario` (
  `usu_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usu_nombre` TEXT NULL DEFAULT NULL,
  `usu_correo` TEXT NULL DEFAULT NULL,
  `usu_telefono` INT(11) NULL DEFAULT NULL,
  `usu_password` TEXT NULL DEFAULT NULL,
  `usu_olvido_password` TEXT NULL DEFAULT NULL,
  `usu_imagen` TEXT NULL DEFAULT NULL,
  `usu_creado` DATETIME NULL DEFAULT NULL,
  `usu_actualizado` DATETIME NULL DEFAULT NULL,
  `usu_estado` ENUM('0', '1') NULL DEFAULT NULL,
  `usu_permiso` ENUM('0', '1') NULL DEFAULT NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tiendacastinblanco`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendacastinblanco`.`compra` (
  `com_id` INT(11) NOT NULL AUTO_INCREMENT,
  `com_precio` FLOAT NULL DEFAULT NULL,
  `com_cantidad` INT(11) NULL DEFAULT NULL,
  `com_creado` DATETIME NULL DEFAULT NULL,
  `com_actualizado` DATETIME NULL,
  `com_estado` ENUM('0', '1') NULL DEFAULT NULL,
  `usu_id` INT(11) NOT NULL,
  PRIMARY KEY (`com_id`),
  INDEX `fk_compra_usuario1_idx` (`usu_id` ASC),
  CONSTRAINT `fk_compra_usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `tiendacastinblanco`.`usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tiendacastinblanco`.`usuario_banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendacastinblanco`.`usuario_banco` (
  `uba_id` INT NOT NULL AUTO_INCREMENT,
  `uba_nombre` VARCHAR(45) NULL,
  `uba_cedula` INT NULL,
  `uba_cuenta` INT(20) NULL,
  `uba_tipocuenta` INT NULL,
  `ban_id` INT(11) NOT NULL,
  PRIMARY KEY (`uba_id`),
  INDEX `fk_usuario_banco_banco1_idx` (`ban_id` ASC),
  CONSTRAINT `fk_usuario_banco_banco1`
    FOREIGN KEY (`ban_id`)
    REFERENCES `tiendacastinblanco`.`banco` (`ban_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendacastinblanco`.`comprobante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendacastinblanco`.`comprobante` (
  `com_id` INT(11) NOT NULL AUTO_INCREMENT,
  `com_tipo` VARCHAR(45) NULL DEFAULT NULL,
  `com_referencia` VARCHAR(45) NULL DEFAULT NULL,
  `com_archivo` TEXT NULL DEFAULT NULL,
  `uba_id` INT NOT NULL,
  PRIMARY KEY (`com_id`),
  INDEX `fk_comprobante_usuario_banco1_idx` (`uba_id` ASC),
  CONSTRAINT `fk_comprobante_usuario_banco1`
    FOREIGN KEY (`uba_id`)
    REFERENCES `tiendacastinblanco`.`usuario_banco` (`uba_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tiendacastinblanco`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendacastinblanco`.`mensaje` (
  `men_id` INT(11) NOT NULL AUTO_INCREMENT,
  `men_asunto` TEXT NULL DEFAULT NULL,
  `men_descripcion` TEXT NULL DEFAULT NULL,
  `men_archivo` TEXT NULL DEFAULT NULL,
  `men_creado` DATETIME NULL DEFAULT NULL,
  `men_actualizado` DATETIME NULL DEFAULT NULL,
  `men_estado` ENUM('0', '1') NULL DEFAULT NULL,
  `usu_id` INT(11) NOT NULL,
  PRIMARY KEY (`men_id`),
  INDEX `fk_mensaje_usuario_idx` (`usu_id` ASC),
  CONSTRAINT `fk_mensaje_usuario`
    FOREIGN KEY (`usu_id`)
    REFERENCES `tiendacastinblanco`.`usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tiendacastinblanco`.`tipo_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendacastinblanco`.`tipo_producto` (
  `tip_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tip_nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Aqui van a ir el tipo de producto, si es liquido se pone en litros y si es solido se pone en kg',
  `tip_peso` VARCHAR(45) NULL DEFAULT NULL COMMENT 'aqui va a ir si es en kg o lt',
  PRIMARY KEY (`tip_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tiendacastinblanco`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendacastinblanco`.`producto` (
  `pro_idproducto` INT(11) NOT NULL AUTO_INCREMENT,
  `pro_nombre` TEXT NULL DEFAULT NULL,
  `pro_precio` FLOAT NULL DEFAULT NULL,
  `pro_cantidad` INT(11) NULL DEFAULT NULL,
  `pro_imagen` TEXT NOT NULL,
  `pro_creado` DATETIME NULL DEFAULT NULL,
  `pro_actualizado` DATETIME NULL DEFAULT NULL,
  `tip_id` INT(11) NOT NULL,
  `pro_estado` ENUM('0', '1') NOT NULL,
  PRIMARY KEY (`pro_idproducto`),
  INDEX `fk_producto_tipo_producto1_idx` (`tip_id` ASC),
  CONSTRAINT `fk_producto_tipo_producto1`
    FOREIGN KEY (`tip_id`)
    REFERENCES `tiendacastinblanco`.`tipo_producto` (`tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tiendacastinblanco`.`transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendacastinblanco`.`transaccion` (
  `tra_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tra_creado` DATETIME NULL DEFAULT NULL,
  `tra_estado` ENUM('0', '1') NULL DEFAULT NULL,
  `com_idcompra` INT(11) NOT NULL,
  `com_idcomprobante` INT(11) NOT NULL,
  PRIMARY KEY (`tra_id`),
  INDEX `fk_transaccion_compra1_idx` (`com_idcompra` ASC),
  INDEX `fk_transaccion_comprobante1_idx` (`com_idcomprobante` ASC),
  CONSTRAINT `fk_transaccion_compra1`
    FOREIGN KEY (`com_idcompra`)
    REFERENCES `tiendacastinblanco`.`compra` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaccion_comprobante1`
    FOREIGN KEY (`com_idcomprobante`)
    REFERENCES `tiendacastinblanco`.`comprobante` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tiendacastinblanco`.`carrito_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendacastinblanco`.`carrito_compra` (
  `car_id` INT NOT NULL AUTO_INCREMENT,
  `car_cantidadproducto` INT NULL,
  `car_precioproductototal` FLOAT NULL,
  `com_idprincipal` INT(11) NOT NULL,
  `pro_id` INT(11) NOT NULL,
  INDEX `fk_carrito_compra_compra1_idx` (`com_idprincipal` ASC),
  INDEX `fk_carrito_compra_producto1_idx` (`pro_id` ASC),
  PRIMARY KEY (`car_id`),
  CONSTRAINT `fk_carrito_compra_compra1`
    FOREIGN KEY (`com_idprincipal`)
    REFERENCES `tiendacastinblanco`.`compra` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_compra_producto1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `tiendacastinblanco`.`producto` (`pro_idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
